name: "Termux"
description: "Official Termux shell environment."
version: "2026.03.29-r1"
type: "termux"

architectures:
  - aarch64: "https://github.com/termux/termux-packages/releases/download/bootstrap-${version}%2Bapt.android-7/bootstrap-aarch64.zip"
    checksum: "d2991fdf49d680b492f77a47a6ac3e7ea242424261e785ac99103302ab7e901d"
  - arm: "https://github.com/termux/termux-packages/releases/download/bootstrap-${version}%2Bapt.android-7/bootstrap-arm.zip"
    checksum: "a2bc2b49e44402117f8d4f8174796c563595b8d664f0a169de973996091c72a1"
  - i686: "https://github.com/termux/termux-packages/releases/download/bootstrap-${version}%2Bapt.android-7/bootstrap-i686.zip"
    checksum: "30184f149312f2076e491321f9fc839e40535d4374280d09fbef7583d0b3dc70"
  - x86_64: "https://github.com/termux/termux-packages/releases/download/bootstrap-${version}%2Bapt.android-7/bootstrap-x86_64.zip"
    checksum: "902b7bfc6dbfb4d3fbaf6044b9a069f349975bd2fb00400f44da2fc2f2b48596"
