name: "Bug report"
description: "Tell us about issue with proot-distro utility"
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        This is a bug tracker of the PRoot Distro - a helper script for PRoot to manage distribution installations. Please use it accordingly to selected ticket type.

        Maintainer may close the bug report without resolution when it doesn't have enough information or when issue considered as result of user mistake.

        > [!IMPORTANT]
        > DISTRIBUTION BUG REPORTS WILL BE DISMISSED
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. You may attach the logs, screenshots, screen video recording and whatever else that will help to understand the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
