name: "Bug report"
description: "Tell us about issue with proot-distro utility"
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        This is a bug tracker of the PRoot Distro - a helper script for PRoot to manage distribution installations. Please use it accordingly to selected ticket type.

        You acknowledge that false or incomplete information will make debugging impossible and you agree to collaborate with maintainers. We may request specific details or to run commands to get more information about the issue.
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. Issue must be backed by proof: log, screenshot, video recording and everything else that will help us to understand the situation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: |
        Give step-by-step instructions to reproduce issue with 100% success rate.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: input
    attributes:
      label: Android OS version
      description: |
        Android version number (e.g. 7.0). If you use proot-distro on a genuine Linux host, put here value 'PC', optionally with name of distribution.
    validations:
      required: true
  - type: input
    attributes:
      label: Kernel information (uname -a)
      description: |
        Put here a complete output of `uname -a`.
    validations:
      required: true
  - type: input
    attributes:
      label: PRoot-Distro version
      description: |
        Put here information from `apt show proot-distro` or from `proot-distro help` version footer.
    validations:
      required: true
  - type: input
    attributes:
      label: PRoot version
      description: |
        Put here information from `proot --version`.
    validations:
      required: true
  - type: input
    attributes:
      label: Termux application version
      description: |
        Full version information about Termux app. Tell whether this is Play Store build, F-Droid or something else. Put value 'PC' if you run proot-distro on a genuine Linux host and not on Termux.
    validations:
      required: true
