name: "Bug report"
description: "Tell us about issue with proot-distro utility"
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        This is a bug tracker of the PRoot Distro - a helper script for PRoot to manage distribution installations. Please use it accordingly to selected ticket type.

        Maintainer may close the bug report without resolution when it doesn't have enough information or when issue considered as result of user mistake.

        > [!IMPORTANT]
        > DISTRIBUTION BUG REPORTS WILL BE DISMISSED
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. Issue must be backed by proof: log, screenshot, video recording and everything else that will help us to understand the situation.

        > [!IMPORTANT]
        > We may request extensive set of information that will help us to determine whether bug is real or happens because of user mistakes: unsupported Termux release, usage of virtual Android such as VMOS/F1VM/VPhoneGaGa/VPhoneApp, custom proot executable, weird Termux configurations, etc. We will close the ticket if you refuse to collaborate.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: |
        Give step-by-step instructions to reproduce issue with 100% success rate.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
