name: "Feature request"
description: "Tell us about function you want to see in proot-distro"
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        This is a bug tracker of the PRoot Distro - a helper script for PRoot to manage distribution installations. Please use it accordingly to selected ticket type.

        Maintainer has right to refuse in adding specific feature for any reason.

        > [!IMPORTANT]
        > DISTRIBUTION REQUESTS WILL BE DISMISSED
  - type: textarea
    attributes:
      label: Feature description
      description: |
        A clear and concise description of a feature you would like to see in `proot-distro`.
    validations:
      required: true
